spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:5432}/account_db
    username: ${DB_CONNECTION_USERNAME:root}
    password: ${DB_CONNECTION_PASSWORD:password}